# rm : 컨테이너 삭제
# rmi : 컨테이너 이미지 삭제
# -d : 백그라운드에서 실행
# -p 80:80 : 호스트의 포트(80)을 컨테이너의 포트(80)과 연결

# 파이프라인 단계 정의
stages:
  - build

build:
  stage: build
  image: docker:latest

  script:
    - echo "Start build"
    - docker stop cinema-hub-container || true
    - docker rm cinema-hub-container || true
    - docker rmi cinema-hub-image || true

    - docker build -t cinema-hub-image .
    - docker run -d --name cinema-hub-container -p 80:80 cinema-hub-image
  tags:
    - backend
  only:
    - main
